# Configuração de Memória da JVM para Compilação Estável
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -Dfile.encoding=UTF-8

# Desativação de Daemon e Concorrência Excessiva no CI/CD
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true

# Suporte ao AndroidX e Jetifier
android.useAndroidX=true
android.enableJetifier=true
